### ISSUE TITLE
User Defined Fields to pull data

### ISSUE THREAD

**Issue by KRinear** [opendns/Deploy-Scripts#2]
Brilliant! I have used the LabTech integration in the past. We are moving to Autotask. I have the component setup and a template job for deployment. How would we automatically pull the Ord ID, Fingerprint and Customer ID from User defined fields that we could create in the applicable sites in AEM? Is that possible?

**Comment by phantom1982** [comment]
Hi, unfortunately AEM does not have the capability to use UDFs like LabTech/Connectwise Automate does. You can find our AEM script here: https://github.com/opendns/Deploy-Scripts/tree/master/AEM

Since AEM doesn't have their own scripting engine like LT or Kaseya, we have to work with existing scripting technologies - in this case we're using primarily PowerShell to accomplish the download and installation of the roaming client. You need to specify the variables when running the script, or possibly store the values and create a unique script for each customer. 

Hope that helps!

**Comment by KRinear** [comment]
Ok. Thanks for the clarification.

Kurt Rinear
Director of Technical Services
Central Texas Technology Solutions
(512) 717-9063 – Direct
(512) 388-5559 – Support
